### ISSUE TITLE
code review

### ISSUE THREAD

**Issue by Amal-Mousa** [GSG-G13/Yasser-Momen#15]
Good job guys, your website looks excellent 💯 .
there are some points to take into consideration next time 
1. try removing the console log and commented-out lines.
2- It's a good idea to have a loader on your page.
Keep up the good work.

**Comment by Dev-MomenQudaih** [comment]
Thanks so much **Amal** & **Eman** 🌹
We will take into consideration the points you mentioned. 😊

**Comment by momenqudaih** [comment]
Thanks so much Amal & Eman 🌹
We will take into consideration the points you mentioned. 😊
